name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-debug:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Build Debug APK
        run: gradle assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LovePlay-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Build Debug APK for Release
        run: gradle assembleDebug
      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
